### ISSUE TITLE
Implement ECMA262 Array builtin object.

### ISSUE THREAD

**Issue by ILyoan** [jerryscript-project/jerryscript#3]
JerryScript Engine support Array builtin object but very limited.
The relevant specification is [ECMA262 15.4](http://www.ecma-international.org/ecma-262/5.1/#sec-15.4)
We need to get it to be done.

Required method/properties:
- [x] Array(..)
- [x] new Array(..)
- [x] Array.prototype
- [x] Array.isArray(..)
- [x] Array.prototype.concat(..) #98 
- [x] Array.prototype.every(..) #84 
- [x] Array.prototype.filter(..) #89
- [x] Array.prototype.forEach(..) #39
- [x] Array.prototype.indexOf(..) #26 
- [x] Array.prototype.join(..) #38 
- [x] Array.prototype.lastIndexOf(..) #77 
- [x] Array.prototype.map(..) #135 
- [x] Array.prototype.pop(..) #22 
- [x] Array.prototype.push(..) #7
- [x] Array.prototype.reduce(..) #104 
- [x] Array.prototype.reduceRight(..) #105 
- [x] Array.prototype.reverse(..) #90 
- [x] Array.prototype.shift(..) #24 
- [x] Array.prototype.slice(..) #78 
- [x] Array.prototype.some(..) #85 
- [x] Array.prototype.sort(..) #95 
- [x] Array.prototype.splice(..) #86
- [x] Array.prototype.toLocaleString(..) #96 
- [x] Array.prototype.toString(..) #36 
- [x] Array.prototype.unshift(..) #25
