### ISSUE TITLE
Implement ECMA262 Object builtin functions

### ISSUE THREAD

**Issue by kkristof** [jerryscript-project/jerryscript#34]
Ecma 262 Objects reference http://www.ecma-international.org/ecma-262/5.1/#sec-15.2

Functions to implement:
- [x] Object(..)
- [x] new Object(..)
- [x] Object.create #209
- [x] Object.defineProperties #37
- [x] Object.defineProperty 
- [x] Object.freeze #202
- [x] Object.getOwnPropertyDescriptor #81
- [x] Object.getOwnPropertyNames #124 
- [x] Object.getPrototypeOf #151 
- [x] Object.isExtensible #106
- [x] Object.isFrozen #202
- [x] Object.isSealed #172
- [x] Object.keys #124 
- [x] Object.preventExtensions #106
- [x] Object.seal #172

Object prototype functions:
- [x] Object.prototype.hasOwnProperty #41 
- [x] Object.prototype.isPrototypeOf #47 
- [x] Object.prototype.propertyIsEnumerable #99 
- [x] Object.prototype.toLocaleString #40
- [x] Object.prototype.toString
- [x] Object.prototype.valueOf
