### ISSUE TITLE
Requirements from IoT.js

### ISSUE THREAD

**Issue by ILyoan** [jerryscript-project/jerryscript#6]
This issue is for all works required from [IoT.js](https://github.com/Samsung/iotjs).

The list of requirements is in https://github.com/Samsung/iotjs/issues/3
- [x] arguments #102 
- [x] Object.create #209
- [x] Object.keys #124 
- [x] Function.prototype.apply #163
- [x] String.prototype.slice #138 

Complete ECMA262 Array builtin object. https://github.com/Samsung/jerryscript/issues/3
- [x] Array.prototype.slice #78 
- [x] Array.prototype.push #7 
- [x] Array.prototype.shift #24
- [x] Array.isArray
